/*
Description

You are given a string stored in a variablestr, and the length of the string is stored in a variable with the nameN

The value stored inNwill always be even

You have to make two strings from the given string, such that the first string contains all the characters in the first half, and the second string contains all the characters present in the second half

For example, if the value stored inN = 6, andstr = "ababcb", then the string generated by the characters in the first half isaba, and the string generated by the characters in the second half isbcb. Since, both the strings are palindromes, the output isyes

Note : The string contains only lower case English Alphabets, and the length of the string will always be an even number

Input
The first line of the input contains the value stored inN

The next line of the input contains the value stored instr


Output
Printyesornobased on the conditions as mentioned in the problem statement

Sample Input 1 

6
ababcb
Sample Output 1

yes
Sample Input 2 

4
abdc
Sample Output 2

no
Sample Input 3 

6
ababba
Sample Output 3

no
Hint

In the first sample test case, the value stored inN = 6andstr = ababcb. The string generated by the first half isaba, while the string generated by the second half isbcb. Since, both the strings are palindrome, the output isyes

In the second sample test case, the value stored inN = 4andstr = abdc. The string generated by the first half isab, while the string generated by the second half isdc. Since, both the strings are not palindrome, the output isno

In the third sample test case, the value stored inN = 6andstr = ababba. The string generated by the first half isaba, while the string generated by the second half isbba. The string generated by the first half is a palindrome but the string generated by the second half is not a plaindrome, therefore the output is no.
  */

function halfPalindrome(N, str) {
  //write code here
  let bag1 = "";
  let bag3 = "";
  for(let i = 0 ; i < N/2; i++){
      bag1 += str[i];
      bag3 += str[(N/2)-1-i];
  }
  let bag2 = "";

  for(let j = N/2; j < N; j++){
      bag2 += str[j];
  }
  let bag4 = "";
  for(let k = N-1; k >= N/2;k--){
      bag4 += str[k]
  }
  if(bag1==bag3 && bag2==bag4){
      console.log("yes");
  }
  else {
      console.log("no");
  }

}